### ISSUE TITLE
New Relic Agent Not Capturing Full Network Requests

### ISSUE THREAD

**Issue by itajenglish** [newrelic/newrelic-react-native-agent#90] opened 2023-04-19 13:30 UTC
I'm observing mobile network errors in the New Relic platform but none of the API requests are showing a response body. It it's only showing the status code.

![Screenshot 2023-04-19 at 10 33 22 AM](https://user-images.githubusercontent.com/889564/233119570-2144c849-628c-41e5-9820-ce6aae1240ed.png)

Agent config:
```
{
  //Android Specific
  // Optional:Enable or disable collection of event data.
  analyticsEventEnabled: true,

  // Optional:Enable or disable crash reporting.
  crashReportingEnabled: true,

  // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
  interactionTracingEnabled: true,

  // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
  networkRequestEnabled: true,

  // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
  networkErrorRequestEnabled: true,

  // Optional:Enable or disable agent logging.
  loggingEnabled: true,

  // iOS Specific
  // Optional:Enable/Disable automatic instrumentation of WebViews
  webViewInstrumentation: true,
};
```

New Relic React Native Agent SDK Version: `1.1.0`
React Native Version: `0.70.8`
Expo SDK Version: `47.0.14`
OS: `iOS`
OS Version: `16.4.1`
Device: iPhone 14 Pro Max

**Comment by ndesai-newrelic** [comment] 2023-04-19 13:33
@itajenglish  can you provide more details?

**Comment by itajenglish** [comment] 2023-04-19 15:13
@ndesai-newrelic Updated

**Comment by ndesai-newrelic** [comment] 2023-04-19 17:11
@itajenglish we will check it from our side, thank you for update

**Comment by kthai-nr** [comment] 2023-04-19 18:24
It might not help since it's already on by default, but try setting `httpResponseBodyCaptureEnabled` to true in your agent config.

**Comment by mbruin-NR** [comment] 2023-04-21 13:58
@itajenglish Thank you for bringing this bug to our attention. I have confirmed that this bug is happening in the iOS agent. I made a ticket for this in our internal bug tracker. Look to our release notes for when a fix for this bug released.

**Closed by mbruin-NR** 2023-04-21 13:58 UTC

**Comment by itajenglish** [comment] 2023-05-27 00:01
The API response body is still not showing in the UI in the latest version of the React Native Agent.

<img width="1048" alt="Screenshot 2023-05-26 at 7 58 23 PM" src="https://github.com/newrelic/newrelic-react-native-agent/assets/889564/dc86322f-bd05-4d63-afe3-f79f9c502f5f">

**Comment by kthai-nr** [comment] 2023-05-30 19:13
@itajenglish The current release has not fixed the issue, but I can confirm that the next release with the updated iOS agent should solve this issue. Are you also getting this problem for android?

**Comment by itajenglish** [comment] 2023-05-30 19:18
> @itajenglish The current release is still missing response bodies on iOS, but I can confirm that the next release with the updated iOS agent should solve this issue. Are you also getting this problem for android as well?

@kthai-nr Thank you for that update! Unfortunately, our Android app is currently broken which we have potentially traced to New Relic and another SDK we use. We are still troubleshooting to be able to provide enough feedback but as of right now we aren't able to get Android to build using New Relic on Expo `48.0.15` and React Native `0.71.7`

**Comment by ndesai-newrelic** [comment] 2024-10-08 13:30
@KarthikBaleneni is it for android or iOS?
