### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by ladp333** [newrelic/newrelic-react-native-agent#64] opened 2023-02-06 22:04 UTC
After adding the newrelic-react-native agent, Our app started crashing every time it is opened and throws the following error. This error occurs in both iOS and Android. 
"react-native": "0.66.5",
"newrelic-react-native-agent": "0.0.9",

Could you please let me know if I have to do something else to fix issue
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FiberNode'
    |     property 'stateNode' -> object with constructor 'ReactNativeFiberHostComponent'
    --- property '_internalFiberInstanceHandleDEV' closes the circle
```
    
    
    
![Cursor_and_iPhone_11](https://user-images.githubusercontent.com/1701042/217096647-b1ff0ddd-4dd4-4729-bc00-e4c25874bab6.png)

I have added the agent in the following way.

=== newrelicReactNativeAgent.js ===

```
import NewRelic from 'newrelic-react-native-agent';
import { Platform } from 'react-native';
import { version } from './package.json';
import { getConfig } from './src/services/configService';

const { NEW_RELIC_APP_TOKEN_ANDROID, NEW_RELIC_APP_TOKEN_IOS } = getConfig();

let appToken;

if (Platform.OS === 'ios') {
  appToken = NEW_RELIC_APP_TOKEN_IOS;
} else {
  appToken = NEW_RELIC_APP_TOKEN_ANDROID;
}

const agentConfiguration = {
  //Android Specific
  // Optional:Enable or disable collection of event data.
  analyticsEventEnabled: true,

  // Optional:Enable or disable crash reporting.
  crashReportingEnabled: true,

  // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
  interactionTracingEnabled: true,

  // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
  networkRequestEnabled: true,

  // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
  networkErrorRequestEnabled: true,

  // Optional:Enable or disable capture of HTTP response bodies for HTTP error traces, and MobileRequestError events.
  httpRequestBodyCaptureEnabled: true,

  //Android Specific
  // Optional: Enable or disable agent logging.
  loggingEnabled: true,

  //iOS Specific
  // Optional:Enable/Disable automatic instrumentation of WebViews
  webViewInstrumentation: true
};

NewRelic.startAgent(appToken, agentConfiguration);
NewRelic.setJSAppVersion(version);
```

=== index.js ===

```
import './newrelicReactNativeAgent'
import 'react-native-gesture-handler';
import 'react-native-url-polyfill/auto';
import { AppRegistry } from 'react-native';
import { decode, encode } from 'base-64';
import { App } from './build/App';


if (!global.btoa) {
  global.btoa = encode;
}

if (!global.atob) {
  global.atob = decode;
}

AppRegistry.registerComponent('MyApp', () => App);
```

**Comment by kthai-nr** [comment] 2023-02-06 22:58
Hello, could you provide any information for reproducing this issue? If possible, could we get the packages that are in `package.json`. This looks like it may require a fix on our end.

**Comment by ladp333** [comment] 2023-02-07 00:27
Hi @kthai-nr 
Thanks for your reply. The following is our dependencies. Tbh, I'm not really sure which one causes the issue. I just added the NR agent as described above and opened the app. Both iOS and Android app crashes in real devices and emulators. Simply the app is 100% unusable after adding the NR agent.

```
"dependencies": {
    "@adobe/react-native-acpanalytics": "^1.3.0",
    "@adobe/react-native-acpcore": "^1.5.1",
    "@adobe/react-native-acptarget": "^1.3.0",
    "@intercom/intercom-react-native": "^3.0.5",
    "@origin-digital/auth-utils": "^1.3.2",
    "@origin-digital/event-dispatcher": "^5.16.10",
    "@origin-digital/mcapp-registry": "^0.14.138",
    "@origin-digital/native-features": "^1.13.123",
    "@origin-digital/platform-enums": "^0.8.2",
    "@origin-digital/reporting-client": "^4.1.1",
    "@origin-digital/style-guide": "^5.8.0",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/clipboard": "^1.5.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-community/slider": "^2.0.7",
    "@react-native-picker/picker": "^2.2.1",
    "base-64": "^0.1.0",
    "newrelic-react-native-agent": "^0.0.9",
    "patch-package": "^6.5.1",
    "path-to-regexp": "^6.1.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "17.0.2",
    "react-native": "0.66.5",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-appboy-sdk": "^1.41.0",
    "react-native-auth0": "1.3.1",
    "react-native-branch": "^5.0.1",
    "react-native-config": "^0.11.7",
    "react-native-device-info": "^5.6.1",
    "react-native-elements": "^2.3.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-in-app-review": "^3.1.1",
    "react-native-inappbrowser-reborn": "^3.4.0",
    "react-native-material-ripple": "^0.9.1",
    "react-native-push-notification": "^7.3.1",
    "react-native-reanimated": "^1.13.1",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.13.0",
    "react-native-secure-key-store": "^2.0.7",
    "react-native-splash-screen": "3.2.0",
    "react-native-svg": "^9.13.3",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^7.5.1",
    "react-navigation": "4.3.3",
    "react-navigation-drawer": "^2.6.0",
    "react-navigation-stack": "^2.10.1",
    "react-navigation-tabs": "^2.10.1",
    "semver": "^6.3.0",
    "styled-components": "^3.3.10",
    "sumo-logger": "^2.8.1",
    "usabilla-react-native": "^0.13.2"
  },

```

What I have done in our staging app for the moment  is that I have patched the ```newrelic-react-native-agent```  package using https://github.com/douglascrockford/JSON-js/blob/master/cycle.js and changed the ```sendConsole``` function to the following.

Let me know if you want me try anything. I'm keen to get this issue fixed and add the NR agent to our app soon.
```
sendConsole(type, args) {
    const argsStr = JSON.stringify(JSON.decycle(args));
    this.send('JSConsole', { consoleType: type, args: argsStr });
    // if (type === 'error') {
    //   this.NRMAModularAgentWrapper.execute('consoleEvents','[JSConsole:Error] ' + argsStr); 
    // }
  }
```

**Comment by kthai-nr** [comment] 2023-02-07 00:32
Thanks for the response. I've pushed out a potential fix that should resolve the issue if you'd like to confirm that this works on your end: https://github.com/newrelic/newrelic-react-native-agent/pull/65/files. We expect to have this out in our next release.

**Comment by ladp333** [comment] 2023-02-07 00:51
@kthai-nr Thanks a lot for the prompt response.  Could let me know when the next release is? Thanks

**Comment by kthai-nr** [comment] 2023-02-07 00:57
@ladp333 No exact date but we are hoping to release sometime this week or next week. I'll notify you via a comment here once we do. Thanks

**Comment by ladp333** [comment] 2023-02-07 20:41
> Thanks for the response. I've pushed out a potential fix that should resolve the issue if you'd like to confirm that this works on your end: https://github.com/newrelic/newrelic-react-native-agent/pull/65/files. We expect to have this out in our next release.

I tested this one. Looks good. Thanks

**Comment by kthai-nr** [comment] 2023-02-10 19:46
Hello we have pushed out the new release with the fixes. We decided to go with the Crockford decycle instead of removing all cyclical structures. Let me know if you run into any other problems. Release is available on npm here: https://www.npmjs.com/package/newrelic-react-native-agent/v/1.0.0

**Comment by kthai-nr** [comment] 2023-02-10 19:47
@ladp333 I'll be closing this issue but feel free to open it back up if you run into any problems.

**Closed by kthai-nr** 2023-02-10 19:47 UTC

**Comment by ladp333** [comment] 2023-02-10 21:18
Thanks @kthai-nr. I have downloaded the latest version. I will raise if I find any issues.

**Comment by ladp333** [comment] 2023-02-10 21:21
> Hello we have pushed out the new release with the fixes. We decided to go with the Crockford decycle instead of removing all cyclical structures. Let me know if you run into any other problems. Release is available on npm here: https://www.npmjs.com/package/newrelic-react-native-agent/v/1.0.0

Great that you opted for Crockford's `decycle` function. As I mentioned that's what I used to patch the NR package when I found this bug and it worked seamlessly.  Cheers !!!
