### ISSUE TITLE
Not compatible with recent version of Android Gradle plugin

### ISSUE THREAD

**Issue by GregoryJego** [newrelic/newrelic-react-native-agent#135] opened 2023-10-24 14:42 UTC
## Description

It is not possible to build a react native app when using last version of `newrelic-react-native-agent` (version 1.3.3) with a recent version of Android Gradle plugin (version 8.0.1)

* Warnings:
```
[newrelic.warn] The New Relic plugin may not be compatible with Android Gradle plugin version 7.4.2.
[newrelic.warn] AGP versions 3.4.0 - 7.1.0 are officially supported.
```

* What went wrong:
```
A problem occurred configuring project ':app'.
> Could not create task ':app:transformClassesWithNewrelicTransformFor...'
> Cannot use @TaskAction annotation on method IncrementalTransformTask.transform() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

**Comment by ndesai-newrelic** [comment] 2023-10-24 19:48
@GregoryJego can you share your Gradle version for this project? we supports AGP version 8.0.1 and higher.

**Comment by GregoryJego** [comment] 2023-10-25 09:21
Hello, we use AGP version 8.0.1. With this version, the app can't be built.

But if we change for an older version like 7.5.1 it works

**Comment by georgetk** [comment] 2023-11-01 12:05
> Hello, we use AGP version 8.0.1. With this version, the app can't be built.
> 
> But if we change for an older version like 7.5.1 it works

I can confirm that this is easily reproducible. I'm getting the below error:

```
A problem occurred configuring project ':app'.
Could not create task ':app:transformClassesWithNewrelicTransformForDevDebug'.
Cannot use @TaskAction annotation on method IncrementalTransformTask.transform() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

When `distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties`

But if it is, `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip` , then no error.

```
"react": "18.2.0",
"react-native": "0.72.6"
"newrelic-react-native-agent": "1.3.3",
```

**Comment by georgetk** [comment] 2023-11-01 14:17
After correctly following the installation steps, I'm now able to resolve the issue.

**Comment by Maxime-Asphalte** [comment] 2023-11-15 14:38
Hello,

I am also facing an issue which could be link to this one.
I am on Expo 49 in a Managed Workflow.

The IOS build worked well and I see infos coming up on the dashboard but on Android the build fail with those errors :

```
> Task :app:newrelicTransformClassesForDebug

Unable to find common super type for androidx/appcompat/view/ContextThemeWrapper and android/content/Context.

Unable to find common super type for com/squareup/kotlinpoet/TypeName and com/google/devtools/ksp/symbol/KSTypeReference.

Unable to find common super type for android/content/Context and com/appsflyer/oaid/OaidClient.

Unable to find common super type for com/appsflyer/oaid/OaidClient$Info and java/lang/Object.

Unable to find common super type for com/appsflyer/oaid/OaidClient and java/lang/Object.

Unable to find common super type for com/appsflyer/oaid/OaidClient$Info and android/content/Context.

Unable to find common super type for com/newrelic/agent/android/ndk/NativeThreadInfo and java/lang/String.

Unable to find common super type for com/newrelic/agent/android/ndk/NativeThreadInfo and java/lang/Object.

Unable to find common super type for java/lang/Throwable and com/google/android/gms/ads/identifier/AdvertisingIdClient$Info.

Unable to find common super type for java/lang/Object and com/google/android/gms/ads/identifier/AdvertisingIdClient$Info.

Unable to find common super type for com/appsflyer/internal/AFf1qSDK and com/android/installreferrer/api/InstallReferrerClient.

Unable to find common super type for com/android/installreferrer/api/InstallReferrerClient and java/lang/Object.

Unable to find common super type for com/android/installreferrer/api/ReferrerDetails and android/content/Context.

Unable to find common super type for com/android/installreferrer/api/ReferrerDetails and java/lang/Object.

Unable to find common super type for com/miui/referrer/api/GetAppsReferrerClient and java/lang/String.

Unable to find common super type for com/miui/referrer/api/GetAppsReferrerDetails and com/miui/referrer/api/GetAppsReferrerClient.

Unable to find common super type for com/miui/referrer/api/GetAppsReferrerClient and java/lang/Object.

Unable to find common super type for com/miui/referrer/api/GetAppsReferrerDetails and java/lang/Object.

Unable to find common super type for java/io/IOException and com/squareup/okhttp/RequestBody.

Unable to find common super type for com/newrelic/agent/android/distributedtracing/TraceContext and okhttp3/Call.

Unable to find common super type for java/io/IOException and okhttp3/RequestBody.

Unable to find common super type for okio/BufferedSource and okio/Buffer.

Unable to find common super type for java/lang/Object and okio/BufferedSource.

> Task :app:newrelicTransformClassesForDebug FAILED

w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:newrelicTransformClassesForDebug'.
```

**Comment by ndesai-newrelic** [comment] 2023-11-16 15:23
@Maxime-Asphalte can you share your Gradle Files and Gradle Version for this issue?

**Comment by freeboub** [comment] 2023-11-16 18:19
Please notice, we are also in a react native environment with @GregoryJego

**Comment by ndesai-newrelic** [comment] 2023-11-17 17:19
@freeboub @Maxime-Asphalte agent is working fine with expo 49. We are unable to reproduce the issue.

**Comment by zsomborgellerfi** [comment] 2023-11-20 16:06
I'm getting the same error on Expo SDK 48 building locally and on the EAS as well. Any ideas?

**Comment by freeboub** [comment] 2023-11-27 08:12
An open discussion is also available here: 
https://forum.newrelic.com/s/hubtopic/aAX8W0000008ezxWAA/android-build-failure-on-apptransformclasseswithnewrelictransformfordebug

**Comment by freeboub** [comment] 2023-11-27 20:30
On our side we upgrade new relic for 6.2.0 to 7.2.0 and review gradle integration, it seems the issue is now fixed.

**Closed** 2023-12-20 15:48 UTC
Labels: bug
