### ISSUE TITLE
Crashing on 1.4.0 with local EAS-CLI EXPO.

### ISSUE THREAD

**Issue by ljmzbigsmart** [newrelic/newrelic-react-native-agent#180] opened 2024-07-26 21:15 UTC
The agent is crashing while trying to build app in local EAS-CLI.

## Description

Just today I tried to build my app with local EAS-CLI as always, and this error keeps popping up, looks like EAS-CLI auto updates dependencies, so this agent gets to 1.4.0

## Steps to Reproduce

Run Expo EAS-CLI build on local machine with 1.4.0 NR agent installed (Expo 51 SDK).

## Expected Behavior

Build not to fail.

## Relevant Logs / Console output

`[RUN_GRADLEW] Error: Unable to resolve module newrelic-react-native-agent/node_modules/react-native-promise-rejection-utils from /private/var/folders/8d/j_b7z8rx7xjdrll3d2f3wglc0000gp/T/eas-build-local-nodejs/416825b9-587c-4dc7-b2c9-9e0673b894f2/build/node_modules/newrelic-react-native-agent/index.js: newrelic-react-native-agent/node_modules/react-native-promise-rejection-utils could not be found within the project or in these directories:
[RUN_GRADLEW]   node_modules
[RUN_GRADLEW]   15 |     getUnhandledPromiseRejectionTracker,
[RUN_GRADLEW]   16 |     setUnhandledPromiseRejectionTracker,
[RUN_GRADLEW] > 17 | } from 'newrelic-react-native-agent/node_modules/react-native-promise-rejection-utils'
[RUN_GRADLEW]      |         ^
[RUN_GRADLEW]   18 |
[RUN_GRADLEW]   19 |
[RUN_GRADLEW]   20 | /**
[RUN_GRADLEW] Error: Unable to resolve module newrelic-react-native-agent/node_modules/react-native-promise-rejection-utils from /private/var/folders/8d/j_b7z8rx7xjdrll3d2f3wglc0000gp/T/eas-build-local-nodejs/416825b9-587c-4dc7-b2c9-9e0673b894f2/build/node_modules/newrelic-react-native-agent/index.js: newrelic-react-native-agent/node_modules/react-native-promise-rejection-utils could not be found within the project or in these directories:
[RUN_GRADLEW]   node_modules
[RUN_GRADLEW]   15 |     getUnhandledPromiseRejectionTracker,
[RUN_GRADLEW]   16 |     setUnhandledPromiseRejectionTracker,
[RUN_GRADLEW] > 17 | } from 'newrelic-react-native-agent/node_modules/react-native-promise-rejection-utils'`

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

`
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "react-native": "0.74.3",
        "expo": "~51.0.21",
        "expo-application": "~5.9.1",
        "expo-asset": "~10.0.10",
        "expo-av": "~14.0.6",
        "expo-barcode-scanner": "~13.0.1",
        "expo-build-properties": "~0.12.3",
        "expo-camera": "~15.0.14",
        "expo-checkbox": "~3.0.0",
        "expo-constants": "~16.0.2",
        "expo-dev-client": "~4.0.20",
        "expo-device": "~6.0.2",
        "expo-file-system": "~17.0.1",
        "expo-image": "~1.12.13",
        "expo-image-manipulator": "~12.0.5",
        "expo-keep-awake": "~13.0.2",
        "expo-linking": "~6.3.1",
        "expo-location": "~17.0.1",
        "expo-status-bar": "~1.12.1",
        "expo-system-ui": "~3.0.7",
        "expo-task-manager": "~11.8.2",
        "expo-updates": "~0.25.20",
        "newrelic-react-native-agent": "^1.3.9",
`

## Additional context

Only using Android builds, iOS project removed entirely.

**Comment by ndesai-newrelic** [comment] 2024-07-26 21:48
@ljmzbigsmart we will look into this issue

**Comment by ndesai-newrelic** [comment] 2024-07-26 22:33
@ljmzbigsmart the issue is fixed in newer published version, we have dependancy issue in 1.4.0 and we unpublished that version. Thank you for your quick feedabck.

**Closed** 2024-07-26 22:34 UTC
Labels: bug
