### ISSUE TITLE
Events not reporting when force kill of an app

### ISSUE THREAD

**Issue by samsonroyquickplay** [newrelic/newrelic-react-native-agent#113] opened 2023-07-20 15:21 UTC
[NOTE]: #  Events not getting triggered when we kill the app

## Description

[NOTE]: # Events not getting triggered in following scenario

## Steps to Reproduce

[NOTE]: # 

1. Launch the app
2. Go to the app details screen
3. Kill the app and see new-relic dashboard events are not reported.

## Expected Behavior

[NOTE]: #  Should trigger all the events tracked previously

## Relevant Logs / Console output

[NOTE]: # No logs

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

ex: If appropriate and possible, it would be helpful to add [Charles traces](https://forum.newrelic.com/s/hubtopic/aAX8W0000008bQlWAI/relic-solution-setting-up-and-collecting-charles-trace-for-android-apps).

**Comment by ndesai-newrelic** [comment] 2023-07-20 15:34
@samsonroyquickplay there is no limitation, it should be recorded .can you specify the platform?

**Comment by samsonroyquickplay** [comment] 2023-07-20 15:47
@ndesai-newrelic its on both iOS and Android.

**Comment by ndesai-newrelic** [comment] 2023-07-21 17:29
@samsonroyquickplay can you share your charles traces for this issue? I am unable to reproduce this issue from my side.

**Comment by amruth-k** [comment] 2023-07-25 09:46
> @samsonroyquickplay can you share your charles traces for this issue? I am unable to reproduce this issue from my side.

1. Launch the application
2. Generate few events
3. kill the application immediately (without putting it in background)

the NR events are not getting reported in the dashboard in this scenario.

**Comment by ndesai-newrelic** [comment] 2023-07-25 16:02
@samsonroyquickplay @amruth-k  how are you killing the app without going into background?

**Comment by dhasvijay** [comment] 2023-07-26 07:44
@ndesai-newrelic These are the steps
1. Open the App 
2. Navigate to different pages(not a necessary step, just to fire events)
3. Kill the app(Swiping up and closing the app, technically it goes to background for less than a second)

While we keep the App in background we don't see any issues 

These are the steps

**Comment by dhasvijay** [comment] 2023-07-31 12:19
@ndesai-newrelic any help on this?

**Comment by ndesai-newrelic** [comment] 2023-07-31 14:22
@dhasvijay we are fixing issue from ios side and we are investigating the same issue from android side too

**Comment by ndesai-newrelic** [comment] 2023-07-31 18:37
@dhasvijay  can you share your code snippet when you force close the app?

**Comment by amruth-k** [comment] 2023-08-01 12:56
This is how we are closing the application:
Steps:
1. Open application
2. Run few events
3. Instantly kill the app without putting it into background.

Note: Try not to put the application in the background for no longer than half a second.

https://github.com/newrelic/newrelic-react-native-agent/assets/122253048/d92312a5-73d8-489f-9a99-46a2d64cbc44

**Comment by dhasvijay** [comment] 2023-08-02 11:57
@ndesai-newrelic let us know if you were able to reproduce on Android

**Comment by ndesai-newrelic** [comment] 2023-08-03 17:42
@dhasvijay still unable to reproduce this issue on android.

**Comment by amruth-k99** [comment] 2023-08-03 20:52
If possible, we can connect over and can help you reproduce the issue.

**Comment by objectiveSee** [comment] 2023-12-13 19:08
If the app crashes then it can't run the networking code needed to send the error to the NewRelic server. Do the crashes eventually show up on New Relic if you re-launch the app after it crashes?

**Comment by dhasvijay** [comment] 2023-12-15 04:23
@objectiveSee no, the events are lost, we don't see them on the dashboard. it will be fine if the SDK fired the pending events upon App re-launch, currently this use case is failing

**Closed** 2024-03-05 22:20 UTC
Labels: bug
